### ISSUE TITLE
Add reference for reused figures?

### ISSUE THREAD

**Issue by ronxin** [fbkarsdorp/doc2vec#1]
Hi! I noticed that you reused two figures and some content from my article "word2vec Parameter Learning Explained". Could you kindly add a reference back to the original article (http://arxiv.org/abs/1411.2738), please? I like you note a lot and look forward to reading more notes like this. Thanks!  -Xin

**Comment by fbkarsdorp** [comment]
Absolutely! Will do.

**Comment by fbkarsdorp** [comment]
@ronxin I updated the notebook. Is it OK with you this way?

**Comment by ronxin** [comment]
Yep. Thank you so much, Folgert!
